spring:
  profiles: dev
  cloud:
    config:
      allow-override: true
      override-none: true
name: test-Dev-Yaml
environment: Dev
servers:
  - www.yahoo.com
  - www.google.com

---
spring:
  profiles: prod
name: test-Prod-Yaml
environment: Prod
servers:
  - www.fedex.com
  - www.ubiquisoft.com